services:
  influxdb:
    image: influxdb:1.8
    container_name: historian-influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: opcuadata
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
    volumes:
      - ./data/influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana-oss:12.3.1
    container_name: historian-grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
      GF_AUTH_DISABLE_LOGIN_FORM: "false"
      GF_SECURITY_COOKIE_SAMESITE: none
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards-json

networks:
  default:
    name: optimwise_historian_net
